default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: LiveLawAPI_development

test:
  <<: *default
  database: LiveLawAPI_test

production:
  <<: *default
  database: LiveLawAPI_production
  username: LiveLawAPI
  password: <%= ENV['LIVELAWAPI_DATABASE_PASSWORD'] %>
